### ISSUE TITLE
Additional IPs and IPv6?

### ISSUE THREAD

**Issue by r33int** [pekare/hetzner-proxmox-pfsense#1]
Hi, I am interested in this setup.

I wanted to know if it is possible to use additional IPs on pfSense, and if it is eventually possible to have the IPv6 subnet to be usable.

Thanks

**Comment by pekare** [comment]
Hi!

It's been a while since I actually used this. Does it even work still? I guess that it might be possible to change the configuration for using IPv6 and/or multiple IPs. But sadly I'm not sure I give you any pointers on how to make that happen.

**Comment by r33int** [comment]
Thank you for your answer. Turns out I got things to work perfectly!
